### ISSUE TITLE
gen-files.js broken due to changes in cryptogen tool

### ISSUE THREAD

**Issue by jorgedr94** [aldredb/cryptogen-ibp#1]
When running `node gen-files.js` the operation fails with the following error:
```Generating orderer file..
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './crypto-config/ordererOrganizations/orderer.example.com/orderers/orderer3.orderer.example.com/msp/admincerts'
    at Object.readdirSync (fs.js:790:3)
    at firstFile (/Users/jorgedr/Documents/projects/cryptogen-ibp/helper.js:54:20)
    at generateComponent (/Users/jorgedr/Documents/projects/cryptogen-ibp/helper.js:64:35)
    at Object.generateOrderers (/Users/jorgedr/Documents/projects/cryptogen-ibp/helper.js:170:23)
    at Object.<anonymous> (/Users/jorgedr/Documents/projects/cryptogen-ibp/gen-files.js:55:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

It looks like the gen-files.js is expecting admincerts to be under the msp/admincerts directory but they are no longer placed there by the crytogen tool.  I found the post below that backs up my theory. 

https://stackoverflow.com/questions/58292383/hyperledger-cryptogen-utility-missing-admin-and-user-pem-cert-in-admincerts-bu

**Comment by aldredb** [comment]
Yes newer versions of `cryptogen` relies on `NodeOU` instead. This is fixed in the latest commit to the code
